# https://travis-ci.org/dr-prodigy/python-holidays
dist: bionic
language: python

before_install:
  - pip install --upgrade pip

# hijri-converter not available < python 3.6
install:
#  - pip install hijri-converter
  - pip install python-dateutil
  - python setup.py install
  - pip install flake8
  - pip install coveralls

matrix:
  include:
    - python: '3.8'
    - python: '3.7'
    - python: '3.6'
    - python: '3.5'
    - python: '2.7'
    - python: 'pypy3'

before_script:
    - flake8 --ignore=F401,W504 constants.py holiday_base.py utils.py holidays/countries/*.py

script:
    - coverage run --omit=*site-packages*,*pypy* tests.py

after_success:
    - coveralls
