# https://travis-ci.org/dr-prodigy/python-holidays
dist: bionic
language: python

python:
    - '3.8'
    - '3.7'
    - '3.6'
    - '3.5'
    - '2.7'
    - 'pypy3'

jobs:
# hijri-converter not available < python 3.6
  include:
    - if: python IN ('3.8', '3.7', '3.6', 'pypy3')
      install: 
        - pip install hijri-converter
        - pip install python-dateutil
        - python setup.py install
        - pip install flake8
        - pip install coveralls
    - if: python IN ('3.5', '2.7')
      install:
        - pip install python-dateutil
        - python setup.py install
        - pip install flake8
        - pip install coveralls

before_script:
    - flake8 --ignore=F401,W504 constants.py holiday_base.py utils.py holidays/countries/*.py

script:
    - coverage run --omit=*site-packages*,*pypy* tests.py

after_success:
    - coveralls
