# https://travis-ci.org/ryanss/holidays.py

language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - pypy

install:
    - python setup.py install
    - pip install flake8
    - pip install coveralls

before_script:
    - flake8 holidays.py tests.py

script:
    - if [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then coverage run --omit=*site-packages*,*pypy* tests.py; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != 3.2 ]]; then coveralls; fi
